---
title: "Calibration plot"
author: "Grace Lyden"
date: "2025-06-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
# base::load("mortality-model.RData")
base::load("mortality_model_test_data.RData")

library(dplyr)
library(haven)
library(survival)
library(ggplot2)
```

## Set up test data with rows after delisting, by week
```{r test}
## Create week variable
test_data = test_data %>% 
  group_by(PX_ID) %>%
  mutate(
    week = row_number()
  ) %>% relocate(week, .after = CAN_LISTING_CTR_CD) %>% ungroup


# Adjust delisting time variables to censor at 6 weeks
# Depending on whether the week is even or odd, this translates to 4 or 5 weeks of follow up after delisting
# If candidates dies more than 4/5 weeks after delisting, they are censored
test_data = test_data %>% group_by(PX_ID) %>% 
  
  mutate(
    # if we have full follow-up for the week, follow for censoring (floor)
    time_until_censor_after_delisting = 
      case_when(row_number() == n() & !is.na(time_until_censor_after_delisting) ~ 
                  floor(pmax(0,removal_time + time_until_censor_after_delisting - interval_stop)/7)*7,
                T ~ NA),
    # follow for death even w/o full week (ceiling)
    time_until_death_after_delisting = 
      case_when(row_number() == n() & !is.na(time_until_death_after_delisting) ~ 
                  ceiling(pmax(0,removal_time + time_until_death_after_delisting - interval_stop)/7)*7,
                T ~ NA)) %>%
  
  fill(time_until_censor_after_delisting,time_until_death_after_delisting,.direction="downup") %>%
  
  ## Note: This is intentionally different from mortality_model_data - 5 weeks regardless of even/odd
  # censor at 6 weeks
  ungroup() %>%
  mutate(time_until_censor_after_delisting = case_when(
    time_until_censor_after_delisting > 35  |
      time_until_death_after_delisting > 35 ~ 35,
    TRUE ~ time_until_censor_after_delisting
  ),
  # recode time to death as missing if censored
  time_until_death_after_delisting = ifelse(!is.na(time_until_censor_after_delisting),NA,
                                            time_until_death_after_delisting),
  outcome = ifelse(!is.na(time_until_censor_after_delisting),0,outcome)
  
  )

## Determine delisting row and # of duplicates we need after delisting, until death or censoring
test_data = test_data %>% group_by(PX_ID) %>% mutate(
  delisting = case_when(
    (!is.na(time_until_death_after_delisting) | !is.na(time_until_censor_after_delisting)) & row_number() == n() ~ 1,
    TRUE ~ 0)
) %>% ungroup() %>% mutate(
  duplicates_after_delisting = case_when(
    delisting == 1 & time_until_death_after_delisting > 0 ~
      time_until_death_after_delisting/7,
    delisting == 1 & time_until_censor_after_delisting > 0 ~ 
      time_until_censor_after_delisting/7,
    TRUE ~ 0))

## repeat rows for the duplicates after delisting
# and recode interval_start, interval_stop
test_data = test_data %>%
  slice(rep(row_number(), duplicates_after_delisting+1)) %>%
  group_by(PX_ID) %>%
  mutate(week=row_number()) %>%
  group_by(PX_ID,duplicates_after_delisting) %>%
  mutate(dup=row_number()-1) %>%
  ungroup() %>%
  mutate(interval_start=ifelse(duplicates_after_delisting>0,interval_start+7*dup,interval_start),
         current_date = as.Date(can_listing_dt) + interval_start,
         interval_stop=ifelse(duplicates_after_delisting>0,interval_stop+7*dup,interval_stop),
         status = if_else(dup>0 & delisting == 1, "off_waitlist", status)) %>%
  select(-dup)

# code outcome for last row - now outcome is correct
test_data = test_data %>%
  group_by(PX_ID) %>%
  mutate(outcome = case_when(
    row_number()==n() & outcome==1 ~ 1,
    row_number()==n() & !is.na(time_until_death_after_delisting) & is.na(time_until_censor_after_delisting) ~ 1,
    T ~ 0))
table(test_data$outcome)
table(test_data$outcome,test_data$CAN_REM_CD)

## Adjust prob_no_tx variable after delisting
# set prob_no_tx to 1 after delisting
test_data = test_data %>%
  group_by(PX_ID) %>%
  mutate(delisting2 = cumsum(delisting),
         prob_no_tx = ifelse(delisting2>1,1,prob_no_tx)) %>%
  ungroup
table(test_data$transplant,test_data$delisting) # quick check
```

## Join test data with 8 intervals
Create start-stop data with up to 6 weeks follow-up for each PX_ID in each interval.

```{r join}
base::load("eight-sets.Rdata")
nrow(eight_sets);eight_sets %>% distinct(PX_ID,current_date) %>% nrow
nrow(test_data);test_data %>% distinct(PX_ID,current_date) %>% nrow
joindat = left_join(test_data,
          eight_sets %>%
            select(PX_ID,current_date,prob_surv_6wk,prob_outcome_6wk) %>%
            mutate(include=T),by=c("PX_ID","current_date"))

# recode week
joindat = joindat %>%
  mutate(int_start = case_when(include ~ 1, T ~ 0)) %>%
  group_by(PX_ID) %>%
  mutate(
    grp = cumsum(int_start)
  ) %>%
  group_by(PX_ID,grp) %>%
  mutate(week_from_baseline = row_number()) %>%
  ungroup() %>%
  filter(week_from_baseline<=6,grp>0)
joindat %>% select(PX_ID,grp,week_from_baseline,current_date,interval_start,interval_stop,outcome)
table(joindat$include)
nrow(eight_sets)
summary(joindat$current_date[joindat$week_from_baseline==1])
table(joindat$outcome)
table(eight_sets$outcome)
```

## Calculate (unstabilized) weights
```{r wts}
# Create weight variable based on prob_no_tx
joindat = joindat %>% group_by(PX_ID, grp) %>% mutate(
  weight = 1/(cumprod(prob_no_tx))
) %>% ungroup()

# remove transplant weeks
joindat = joindat %>% filter(transplant == 0)

# look at weights
with(joindat,tapply(weight,week_from_baseline,summary))

## calculate stabilized weights

# get variables at start
joindat = joindat %>% 
  group_by(PX_ID,grp) %>% 
  mutate(albumin_at_start = first(albumin),
         bilirubin_at_start = first(bilirubin),
         eGFR_at_start = first(eGFR),
         sodium_at_start = first(sodium),
         BNP_at_start = first(BNP),
         BNP_NT_Pro_at_start = first(BNP_NT_Pro),
         durable_LVAD_at_start = first(durable_LVAD),
         short_mcs_ever_at_start = first(short_MCS_ever)) %>% 
  ungroup

# calculate numerator
base::load("mortality-model.RData")
joindat = joindat %>% mutate(
  prob_no_tx_start = 1 - 
    predict(tx_model_first, newdata = joindat, type = "response"),
  prob_no_tx_start = ifelse(delisting2>1,1,prob_no_tx_start)) %>%
  group_by(PX_ID, grp) %>% mutate(
  sweight = cumprod(prob_no_tx_start)/(cumprod(prob_no_tx))
) %>% ungroup
with(joindat,tapply(sweight,week_from_baseline,summary))

# truncate weights
joindat = joindat %>% group_by(week_from_baseline) %>% mutate(
  tweight = ifelse(sweight > quantile(sweight,probs=.98,na.rm=T), 
                   quantile(sweight,probs=.98,na.rm=T), sweight),
  tweight = ifelse(sweight < quantile(sweight,probs=.02,na.rm=T), 
                   quantile(sweight,probs=.02,na.rm=T), tweight)) %>%
  ungroup
with(joindat,tapply(tweight,week_from_baseline,summary))


```


## Make calibration plot
```{r calib}
makeCalibData = function(data,q=10) {
  # group data into ntiles by expected risk
  data1 = data %>% filter(week_from_baseline==1)
  data1$risk_grp = ntile(data1$prob_outcome_6wk,n = q)
  data = left_join(data,data1 %>% select(PX_ID,grp,risk_grp),by=c("PX_ID","grp"))
  
  # get average predicted risk in each ntile
  df = data1 %>% group_by(risk_grp) %>% 
    summarise(exp=mean(prob_outcome_6wk),
              exp.05=quantile(prob_outcome_6wk,.25),
              exp.95=quantile(prob_outcome_6wk,.75))
  
  # get observed risk in each ntile
  obs_risks = lapply(1:q,function(i) {
    ipw.surv = survfit(Surv(start,stop,outcome) ~ 1,
                      data=data %>% filter(risk_grp==i) %>%
                        mutate(start=week_from_baseline-1,
                               stop=week_from_baseline,
                               id=interaction(PX_ID,grp)),
                      type='kaplan-meier', weights=sweight,
                      cluster=id)
    ipw.CI = summary(ipw.surv,times=6,extend=T)[c("surv","lower","upper")]
    # convert to mortality
    mort.CI = lapply(ipw.CI,function(surv) {1-surv})
    return(mort.CI)
  })
  obs_df = do.call(rbind.data.frame,obs_risks) %>%
    rename(obs=surv,upper=lower,lower=upper)
  output_df = cbind.data.frame(df,obs_df)
  return(output_df)
}
calibdat = makeCalibData(joindat,20)

library(ggforce)
ggplot(calibdat,aes(x=exp,y=obs)) +
  # geom_smooth(method = "lm", se = FALSE, linetype="dashed", fullrange=T,
  #             linewidth=.5,alpha=.75) +
  geom_abline(intercept=0,slope=1,color="darkgrey") +
  geom_errorbar(aes(ymin=lower,ymax=upper)) +
  geom_point(size=2,alpha=.8) + 
  scale_x_continuous(limits=c(0,.15)) +
  scale_y_continuous(limits=c(0,.15),
                     oob = scales::rescale_none) +
  # coord_cartesian(xlim=c(0,.15),ylim=c(0,.15)) +
  facet_zoom(xlim=c(0,.05),ylim=c(0,.05),zoom.size=1,show.area=F) +  
  theme_bw() +
  theme(text=element_text(size=14)) +
  labs(y="Observed 6-week mortality probability",x="Expected 6-week mortality probability")
ggsave("calib-overall.png",width=8,height=4)


# by status
joindat = joindat %>% group_by(PX_ID,grp) %>% mutate(status_at_start=first(status)) %>% ungroup
table(joindat$status_at_start)
table(joindat$status)

# get overall observed and expected by status
calib_status = lapply(1:6,function(i) {
  makeCalibData(joindat %>% filter(status_at_start==i),q=1) %>%
    mutate(status=i) %>% relocate(status,.before=exp) %>% select(-risk_grp)
})
calib_status = do.call(rbind.data.frame,calib_status)

# make bar plot by status
calib_status_long = calib_status %>%
  pivot_longer(cols = c(exp, obs), names_to = "type", values_to = "value") %>%
  mutate(lower=ifelse(type=="exp",exp.05,lower),
         upper=ifelse(type=="exp",exp.95,upper),
         type_fact = factor(type,levels=c("exp","obs"),
                            labels=c("Predicted\n(US-CRS 2.0)",
                                     "Observed")))
ggplot(calib_status_long,
       aes(x = factor(status), y = value, fill = type_fact)) +
  geom_col(position = position_dodge(width = 0.9), color = "black") +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    position = position_dodge(width = 0.9),
    width = 0.2
  ) +
  coord_cartesian(ylim=c(0,.4)) +
  scale_fill_manual(values = c("Predicted\n(US-CRS 2.0)" = "white", "Observed" = "gray40")) +
  labs(x = "Status", y = "6-Week Mortality Probability", fill = NULL) +
  theme_bw() + theme(text=element_text(size=14))
ggsave("calib-by-status.png",width=7.5,height=6.5)
```
